/// Mapping tables from Typst symbol names to LaTeX commands,
/// and Typst math shorthands to symbol names.
///
/// Derived from the `typst-symbols` Haskell package and the
/// `typstSymbolMap` / `getAccentCommand` in `Writers/Typst.hs`.

use std::collections::HashMap;
use std::sync::LazyLock;

/// Typst symbol name -> LaTeX command.
pub static SYMBOL_MAP: LazyLock<HashMap<&'static str, &'static str>> = LazyLock::new(|| {
    let entries: &[(&str, &str)] = &[
        // Greek lowercase
        ("alpha", "\\alpha"),
        ("beta", "\\beta"),
        ("gamma", "\\gamma"),
        ("delta", "\\delta"),
        ("epsilon", "\\epsilon"),
        ("epsilon.alt", "\\varepsilon"),
        ("zeta", "\\zeta"),
        ("eta", "\\eta"),
        ("theta", "\\theta"),
        ("theta.alt", "\\vartheta"),
        ("iota", "\\iota"),
        ("kappa", "\\kappa"),
        ("lambda", "\\lambda"),
        ("mu", "\\mu"),
        ("nu", "\\nu"),
        ("xi", "\\xi"),
        ("pi", "\\pi"),
        ("pi.alt", "\\varpi"),
        ("rho", "\\rho"),
        ("rho.alt", "\\varrho"),
        ("sigma", "\\sigma"),
        ("sigma.alt", "\\varsigma"),
        ("tau", "\\tau"),
        ("upsilon", "\\upsilon"),
        ("phi", "\\phi"),
        ("phi.alt", "\\varphi"),
        ("chi", "\\chi"),
        ("psi", "\\psi"),
        ("omega", "\\omega"),
        // Greek uppercase
        ("Gamma", "\\Gamma"),
        ("Delta", "\\Delta"),
        ("Theta", "\\Theta"),
        ("Lambda", "\\Lambda"),
        ("Xi", "\\Xi"),
        ("Pi", "\\Pi"),
        ("Sigma", "\\Sigma"),
        ("Upsilon", "\\Upsilon"),
        ("Phi", "\\Phi"),
        ("Psi", "\\Psi"),
        ("Omega", "\\Omega"),
        // Binary operators
        ("plus", "+"),
        ("minus", "-"),
        ("plus.minus", "\\pm"),
        ("minus.plus", "\\mp"),
        ("times", "\\times"),
        ("div", "\\div"),
        ("ast", "\\ast"),
        ("star", "\\star"),
        ("circle.stroked.tiny", "\\circ"),
        ("circle.stroked.small", "\\circ"),
        ("dot.op", "\\cdot"),
        ("bullet", "\\bullet"),
        ("diamond.stroked", "\\diamond"),
        ("triangle.stroked.t", "\\bigtriangleup"),
        ("triangle.stroked.b", "\\bigtriangledown"),
        ("wreath", "\\wr"),
        ("circle.plus", "\\oplus"),
        ("circle.minus", "\\ominus"),
        ("circle.times", "\\otimes"),
        ("circle.dot", "\\odot"),
        ("square.plus", "\\boxplus"),
        ("square.minus", "\\boxminus"),
        ("square.times", "\\boxtimes"),
        ("square.dot", "\\boxdot"),
        ("and", "\\wedge"),
        ("or", "\\vee"),
        ("union", "\\cup"),
        ("sect", "\\cap"),
        ("union.sq", "\\sqcup"),
        ("sect.sq", "\\sqcap"),
        ("union.plus", "\\uplus"),
        ("without", "\\setminus"),
        ("dagger", "\\dagger"),
        ("dagger.double", "\\ddagger"),
        ("tack.r", "\\vdash"),
        ("tack.l", "\\dashv"),
        ("tack.t", "\\bot"),
        ("tack.b", "\\top"),
        ("top", "\\top"),
        ("bot", "\\bot"),
        // Relations
        ("lt.eq", "\\leq"),
        ("gt.eq", "\\geq"),
        ("lt.eq.slant", "\\leqslant"),
        ("gt.eq.slant", "\\geqslant"),
        ("prec", "\\prec"),
        ("prec.eq", "\\preceq"),
        ("succ", "\\succ"),
        ("succ.eq", "\\succeq"),
        ("tilde.op", "\\sim"),
        ("tilde.eq", "\\simeq"),
        ("tilde.equiv", "\\cong"),
        ("approx", "\\approx"),
        ("eq.triple", "\\equiv"),
        ("subset", "\\subset"),
        ("supset", "\\supset"),
        ("subset.eq", "\\subseteq"),
        ("supset.eq", "\\supseteq"),
        ("subset.sq", "\\sqsubseteq"),
        ("supset.sq", "\\sqsupseteq"),
        ("in", "\\in"),
        ("in.not", "\\notin"),
        ("eq.not", "\\neq"),
        ("prop", "\\propto"),
        ("models", "\\models"),
        ("perp", "\\perp"),
        ("parallel", "\\parallel"),
        ("mid", "\\mid"),
        // Arrows
        ("arrow.r", "\\rightarrow"),
        ("arrow.l", "\\leftarrow"),
        ("arrow.t", "\\uparrow"),
        ("arrow.b", "\\downarrow"),
        ("arrow.r.double", "\\Rightarrow"),
        ("arrow.l.double", "\\Leftarrow"),
        ("arrow.t.double", "\\Uparrow"),
        ("arrow.b.double", "\\Downarrow"),
        ("arrow.l.r", "\\leftrightarrow"),
        ("arrow.l.r.double", "\\Leftrightarrow"),
        ("arrow.r.long", "\\longrightarrow"),
        ("arrow.l.long", "\\longleftarrow"),
        ("arrow.r.long.double", "\\Longrightarrow"),
        ("arrow.l.long.double", "\\Longleftarrow"),
        ("arrow.r.long.bar", "\\longmapsto"),
        ("arrow.r.bar", "\\mapsto"),
        ("arrow.r.hook", "\\hookrightarrow"),
        ("arrow.l.hook", "\\hookleftarrow"),
        ("arrow.r.squiggly", "\\rightsquigarrow"),
        ("harpoon.rt", "\\rightharpoonup"),
        ("harpoon.rb", "\\rightharpoondown"),
        ("harpoon.lt", "\\leftharpoonup"),
        ("harpoon.lb", "\\leftharpoondown"),
        ("harpoons.rtlb", "\\rightleftharpoons"),
        // Large operators
        ("sum", "\\sum"),
        ("product", "\\prod"),
        ("product.co", "\\coprod"),
        ("integral", "\\int"),
        ("integral.double", "\\iint"),
        ("integral.triple", "\\iiint"),
        ("integral.cont", "\\oint"),
        ("union.big", "\\bigcup"),
        ("sect.big", "\\bigcap"),
        ("or.big", "\\bigvee"),
        ("and.big", "\\bigwedge"),
        ("plus.big", "\\bigoplus"),
        ("times.big", "\\bigotimes"),
        ("dot.big", "\\bigodot"),
        ("union.sq.big", "\\bigsqcup"),
        ("union.plus.big", "\\biguplus"),
        // Dots
        ("dots", "\\dots"),
        ("dots.h", "\\cdots"),
        ("dots.h.c", "\\cdots"),
        ("dots.c", "\\cdots"),
        ("dots.v", "\\vdots"),
        ("dots.down", "\\ddots"),
        ("dots.up", "\\iddots"),
        // Misc symbols
        ("infinity", "\\infty"),
        ("emptyset", "\\emptyset"),
        ("nothing", "\\varnothing"),
        ("nabla", "\\nabla"),
        ("partial", "\\partial"),
        ("planck.reduce", "\\hbar"),
        ("ell", "\\ell"),
        ("Re", "\\Re"),
        ("Im", "\\Im"),
        ("aleph", "\\aleph"),
        ("forall", "\\forall"),
        ("exists", "\\exists"),
        ("exists.not", "\\nexists"),
        ("not", "\\neg"),
        ("angle", "\\angle"),
        ("angle.arc", "\\measuredangle"),
        ("triangle.stroked.r", "\\triangleright"),
        ("triangle.stroked.l", "\\triangleleft"),
        // Delimiters
        ("paren.l", "("),
        ("paren.r", ")"),
        ("bracket.l", "["),
        ("bracket.r", "]"),
        ("brace.l", "\\{"),
        ("brace.r", "\\}"),
        ("angle.l", "\\langle"),
        ("angle.r", "\\rangle"),
        ("bar.v", "|"),
        ("bar.v.double", "\\|"),
        ("floor.l", "\\lfloor"),
        ("floor.r", "\\rfloor"),
        ("ceil.l", "\\lceil"),
        ("ceil.r", "\\rceil"),
        // Spacing
        ("space", "\\ "),
        // Other common
        ("compose", "\\circ"),
        ("colon", "\\colon"),
        ("checkmark", "\\checkmark"),
    ];
    entries.iter().cloned().collect()
});

/// Math shorthand sequences -> Typst symbol names.
/// Derived from `mathSymbolShorthands` in the typst-symbols package.
pub static SHORTHANDS: LazyLock<Vec<(&'static str, &'static str)>> = LazyLock::new(|| {
    // Sorted longest-first for greedy matching.
    let mut v: Vec<(&str, &str)> = vec![
        ("...", "dots"),
        ("-->", "arrow.r.long"),
        ("<--", "arrow.l.long"),
        ("<->", "arrow.l.r"),
        ("==>", "arrow.r.long.double"),
        ("<==", "arrow.l.long.double"),
        ("<=>", "arrow.l.r.double"),
        ("|->", "arrow.r.bar"),
        ("|=>", "arrow.r.double.bar"),
        ("~~", "tilde.op"),
        ("~=", "tilde.eq"),
        (">>", "gt.double"),
        ("<<", "lt.double"),
        ("->", "arrow.r"),
        ("<-", "arrow.l"),
        ("=>", "arrow.r.double"),
        ("<=", "lt.eq"),
        (">=", "gt.eq"),
        ("!=", "eq.not"),
        (":=", "colon.eq"),
        ("::=", "colon.double.eq"),
        ("[|", "bracket.l.double"),
        ("|]", "bracket.r.double"),
        ("||", "bar.v.double"),
        ("+-", "plus.minus"),
        ("-+", "minus.plus"),
        ("~", "tilde.op"),
        ("*", "ast"),
    ];
    v.sort_by(|a, b| b.0.len().cmp(&a.0.len()));
    v
});

/// Typst accent name -> LaTeX accent command.
/// Reverse of `getAccentCommand` in `Writers/Typst.hs`.
pub static ACCENT_MAP: LazyLock<HashMap<&'static str, &'static str>> = LazyLock::new(|| {
    let entries: &[(&str, &str)] = &[
        ("hat", "\\hat"),
        ("tilde", "\\tilde"),
        ("dot", "\\dot"),
        ("dot.double", "\\ddot"),
        ("dot.triple", "\\dddot"),
        ("dot.quad", "\\ddddot"),
        ("diaer", "\\ddot"),
        ("acute", "\\acute"),
        ("grave", "\\grave"),
        ("macron", "\\bar"),
        ("overline", "\\overline"),
        ("breve", "\\breve"),
        ("caron", "\\check"),
        ("circle", "\\mathring"),
        ("arrow", "\\vec"),
        ("arrow.r", "\\overrightarrow"),
        ("arrow.l", "\\overleftarrow"),
        ("arrow.l.r", "\\overleftrightarrow"),
        ("harpoon", "\\overset{\\rightharpoonup}"),
        ("harpoon.lt", "\\overset{\\leftharpoonup}"),
    ];
    entries.iter().cloned().collect()
});

/// Predefined Typst math operators that map directly to LaTeX operator commands.
/// From `predefinedOperators` in `Module/Math.hs`.
pub static PREDEFINED_OPERATORS: LazyLock<HashMap<&'static str, (&'static str, bool)>> =
    LazyLock::new(|| {
        let entries: &[(&str, &str, bool)] = &[
            // With limits
            ("lim", "\\lim", true),
            ("limsup", "\\limsup", true),
            ("liminf", "\\liminf", true),
            ("det", "\\det", true),
            ("gcd", "\\gcd", true),
            ("inf", "\\inf", true),
            ("max", "\\max", true),
            ("min", "\\min", true),
            ("Pr", "\\Pr", true),
            ("sup", "\\sup", true),
            // Without limits
            ("arccos", "\\arccos", false),
            ("arcsin", "\\arcsin", false),
            ("arctan", "\\arctan", false),
            ("arg", "\\arg", false),
            ("cos", "\\cos", false),
            ("cosh", "\\cosh", false),
            ("cot", "\\cot", false),
            ("coth", "\\coth", false),
            ("csc", "\\csc", false),
            ("deg", "\\deg", false),
            ("dim", "\\dim", false),
            ("exp", "\\exp", false),
            ("hom", "\\hom", false),
            ("ker", "\\ker", false),
            ("lg", "\\lg", false),
            ("ln", "\\ln", false),
            ("log", "\\log", false),
            ("mod", "\\mod", false),
            ("sec", "\\sec", false),
            ("sin", "\\sin", false),
            ("sinh", "\\sinh", false),
            ("tan", "\\tan", false),
            ("tanh", "\\tanh", false),
            // Non-standard LaTeX operators (use operatorname)
            ("csch", "\\operatorname{csch}", false),
            ("sech", "\\operatorname{sech}", false),
            ("sinc", "\\operatorname{sinc}", false),
            ("ctg", "\\operatorname{ctg}", false),
            ("tg", "\\operatorname{tg}", false),
            ("id", "\\operatorname{id}", true),
            ("im", "\\operatorname{im}", true),
            ("tr", "\\operatorname{tr}", true),
            ("lcm", "\\operatorname{lcm}", false),
        ];
        entries.iter().map(|(k, v, l)| (*k, (*v, *l))).collect()
    });
