// Generated by Calepin. Do not edit.

#let config = (
  enabled: true,
  results: path("results.json"),
  "image-meta": path("image-meta.json"),
  "source-dir": "",
  source: "compile_watch_serve.typ",
  "raw-langs": ("d2", "dot", "mermaid", "powershell", "python", "r", "sh", "tikz"),
)
