title = "Calepin"
description = "A Typst-native computational notebook and static website generator."
base_url = "https://vincentarelbundock.github.io/calepin"
logo = "assets/logo_short_2.svg"
logo_alt = "Calepin"
github_url = "https://github.com/vincentarelbundock/calepin"

[executables]
python = ".venv/bin/python"
typst = "typst"

[sidebar]

[[sidebar.section]]
title = "Getting started"

  [[sidebar.section.item]]
  path = "index.typ"
  label = "Home"

  [[sidebar.section.item]]
  path = "install.typ"
  label = "Install"

  [[sidebar.section.item]]
  path = "config.typ"
  label = "Configuration"

[[sidebar.section]]
title = "Code execution"

  [[sidebar.section.item]]
  path = "supported-languages.typ"
  label = "Languages"

  [[sidebar.section.item]]
  path = "options.typ"
  label = "Options"

  [[sidebar.section.item]]
  path = "parameterized_notebooks.typ"
  label = "Parameterized notebooks"

  [[sidebar.section.item]]
  path = "tables_and_figures.typ"
  label = "Tables and figures"

  [[sidebar.section.item]]
  path = "crossreferences.typ"
  label = "Cross-references"

[[sidebar.section]]
title = "Roadmap"

  [[sidebar.section.item]]
  path = "website_generator.typ"
  label = "Website generator"

  [[sidebar.section.item]]
  path = "templates.typ"
  label = "Templates"

[[sidebar.section]]
title = "Reference"

  [[sidebar.section.item]]
  path = "cli.typ"
  label = "Command line"

  [[sidebar.section.item]]
  path = "example.typ"
  label = "Example notebook"
