[project]
site_name = "Calepin"
site_description = "Experimental Typst preprocessor for executable code chunks."
site_author = "Vincent Arel-Bundock"
site_url = "https://vincentarelbundock.github.io/calepin/"
repo_url = "https://github.com/vincentarelbundock/calepin"
repo_name = "vincentarelbundock/calepin"
docs_dir = "docs-src"
site_dir = "docs"
use_directory_urls = false
copyright = "Calepin is distributed under the MIT License."
extra_css = ["assets/stylesheets/extra.css"]
nav = [
  { "Home" = "index.html" },
  { "Supported Languages" = "supported-languages.html" },
  { "Options" = "options.html" },
  { "Tables and Figures" = "tables_and_figures.html" },
  { "Configuration" = "config.html" },
  { "Templates" = "templates.html" },
  { "CLI" = "cli.html" },
  { "example.typ" = "example-typst.html" },
  { "example.pdf" = "example-pdf.html" },
  { "example.html" = "example-html.html" },
]

[project.theme]
language = "en"
custom_dir = "docs-src/overrides"
favicon = "assets/logo_short_2.svg"
icon.logo = "calepin/logo_short_2"
features = [
  "content.code.copy",
  "navigation.top",
  "navigation.tracking",
  "search.highlight",
]

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.markdown_extensions.admonition]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions."zensical.extensions.macros"]
module_name = "docs-support/macros"
on_error_fail = true
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.toc]
permalink = true
toc_depth = "2-3"
[project.markdown_extensions.pymdownx.highlight]
pygments_lang_class = true
[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" }
]
