// Generated by Calepin. Do not edit.

#let config = (
  enabled: true,
  results: path("results.json"),
  "image-meta": path("image-meta.json"),
  "source-dir": "getting-started",
  source: "getting-started/config.typ",
  "raw-langs": ("bash", "d2", "dot", "mermaid", "python", "r", "tikz", "toml"),
)
