name = "website"
description = "Multi-page website"
inherits = "html"

[target]
embed_resources = false
modules = ["highlight", "append_footnotes", "embed_images"]

[assets]
static = ["fontawesome/"]

[[modules]]
name = "site_wrap"
kind = "project"
