name = "website"
description = "Multi-page website styled with Tailwind CSS"
inherits = "html"
collection = true

[target]
standalone = false
modules = ["highlight", "append_footnotes", "embed_images"]

[assets]
static = ["fontawesome/"]

[[modules]]
name = "site_wrap"
kind = "project"
