name = "book"
description = "Multi-chapter book"
inherits = "html"
collection = true

[scaffold.book]

[target]
modules = ["highlight", "append_footnotes"]

[[modules]]
name = "orchestrator"
kind = "project"
