/// Mapping tables from LaTeX commands to Typst math identifiers.
///
/// These are the reverse of the maps in the `typst_to_latex` plugin.

use std::collections::HashMap;
use std::sync::LazyLock;

/// LaTeX command -> Typst symbol name.
pub static SYMBOL_MAP: LazyLock<HashMap<&'static str, &'static str>> = LazyLock::new(|| {
    let entries: &[(&str, &str)] = &[
        // Greek lowercase
        ("\\alpha", "alpha"),
        ("\\beta", "beta"),
        ("\\gamma", "gamma"),
        ("\\delta", "delta"),
        ("\\epsilon", "epsilon"),
        ("\\varepsilon", "epsilon.alt"),
        ("\\zeta", "zeta"),
        ("\\eta", "eta"),
        ("\\theta", "theta"),
        ("\\vartheta", "theta.alt"),
        ("\\iota", "iota"),
        ("\\kappa", "kappa"),
        ("\\lambda", "lambda"),
        ("\\mu", "mu"),
        ("\\nu", "nu"),
        ("\\xi", "xi"),
        ("\\pi", "pi"),
        ("\\varpi", "pi.alt"),
        ("\\rho", "rho"),
        ("\\varrho", "rho.alt"),
        ("\\sigma", "sigma"),
        ("\\varsigma", "sigma.alt"),
        ("\\tau", "tau"),
        ("\\upsilon", "upsilon"),
        ("\\phi", "phi"),
        ("\\varphi", "phi.alt"),
        ("\\chi", "chi"),
        ("\\psi", "psi"),
        ("\\omega", "omega"),
        // Greek uppercase
        ("\\Gamma", "Gamma"),
        ("\\Delta", "Delta"),
        ("\\Theta", "Theta"),
        ("\\Lambda", "Lambda"),
        ("\\Xi", "Xi"),
        ("\\Pi", "Pi"),
        ("\\Sigma", "Sigma"),
        ("\\Upsilon", "Upsilon"),
        ("\\Phi", "Phi"),
        ("\\Psi", "Psi"),
        ("\\Omega", "Omega"),
        // Binary operators
        ("\\pm", "plus.minus"),
        ("\\mp", "minus.plus"),
        ("\\times", "times"),
        ("\\div", "div"),
        ("\\ast", "ast"),
        ("\\star", "star"),
        ("\\circ", "compose"),
        ("\\cdot", "dot.op"),
        ("\\bullet", "bullet"),
        ("\\diamond", "diamond.stroked"),
        ("\\bigtriangleup", "triangle.stroked.t"),
        ("\\bigtriangledown", "triangle.stroked.b"),
        ("\\wr", "wreath"),
        ("\\oplus", "circle.plus"),
        ("\\ominus", "circle.minus"),
        ("\\otimes", "circle.times"),
        ("\\odot", "circle.dot"),
        ("\\boxplus", "square.plus"),
        ("\\boxminus", "square.minus"),
        ("\\boxtimes", "square.times"),
        ("\\boxdot", "square.dot"),
        ("\\wedge", "and"),
        ("\\vee", "or"),
        ("\\cup", "union"),
        ("\\cap", "sect"),
        ("\\sqcup", "union.sq"),
        ("\\sqcap", "sect.sq"),
        ("\\uplus", "union.plus"),
        ("\\setminus", "without"),
        ("\\dagger", "dagger"),
        ("\\ddagger", "dagger.double"),
        ("\\vdash", "tack.r"),
        ("\\dashv", "tack.l"),
        ("\\top", "top"),
        ("\\bot", "bot"),
        // Relations
        ("\\leq", "lt.eq"),
        ("\\le", "lt.eq"),
        ("\\geq", "gt.eq"),
        ("\\ge", "gt.eq"),
        ("\\leqslant", "lt.eq.slant"),
        ("\\geqslant", "gt.eq.slant"),
        ("\\prec", "prec"),
        ("\\preceq", "prec.eq"),
        ("\\succ", "succ"),
        ("\\succeq", "succ.eq"),
        ("\\sim", "tilde.op"),
        ("\\simeq", "tilde.eq"),
        ("\\cong", "tilde.equiv"),
        ("\\approx", "approx"),
        ("\\equiv", "eq.triple"),
        ("\\subset", "subset"),
        ("\\supset", "supset"),
        ("\\subseteq", "subset.eq"),
        ("\\supseteq", "supset.eq"),
        ("\\sqsubseteq", "subset.sq"),
        ("\\sqsupseteq", "supset.sq"),
        ("\\in", "in"),
        ("\\notin", "in.not"),
        ("\\neq", "eq.not"),
        ("\\ne", "eq.not"),
        ("\\propto", "prop"),
        ("\\models", "models"),
        ("\\perp", "perp"),
        ("\\parallel", "parallel"),
        ("\\mid", "mid"),
        ("\\gg", "gt.double"),
        ("\\ll", "lt.double"),
        ("\\coloneqq", "colon.eq"),
        ("\\Coloneqq", "colon.double.eq"),
        // Arrows
        ("\\rightarrow", "arrow.r"),
        ("\\to", "arrow.r"),
        ("\\leftarrow", "arrow.l"),
        ("\\gets", "arrow.l"),
        ("\\uparrow", "arrow.t"),
        ("\\downarrow", "arrow.b"),
        ("\\Rightarrow", "arrow.r.double"),
        ("\\Leftarrow", "arrow.l.double"),
        ("\\Uparrow", "arrow.t.double"),
        ("\\Downarrow", "arrow.b.double"),
        ("\\leftrightarrow", "arrow.l.r"),
        ("\\Leftrightarrow", "arrow.l.r.double"),
        ("\\longrightarrow", "arrow.r.long"),
        ("\\longleftarrow", "arrow.l.long"),
        ("\\Longrightarrow", "arrow.r.long.double"),
        ("\\Longleftarrow", "arrow.l.long.double"),
        ("\\longmapsto", "arrow.r.long.bar"),
        ("\\mapsto", "arrow.r.bar"),
        ("\\Mapsto", "arrow.r.double.bar"),
        ("\\hookrightarrow", "arrow.r.hook"),
        ("\\hookleftarrow", "arrow.l.hook"),
        ("\\rightsquigarrow", "arrow.r.squiggly"),
        ("\\rightharpoonup", "harpoon.rt"),
        ("\\rightharpoondown", "harpoon.rb"),
        ("\\leftharpoonup", "harpoon.lt"),
        ("\\leftharpoondown", "harpoon.lb"),
        ("\\rightleftharpoons", "harpoons.rtlb"),
        // Large operators
        ("\\sum", "sum"),
        ("\\prod", "product"),
        ("\\coprod", "product.co"),
        ("\\int", "integral"),
        ("\\iint", "integral.double"),
        ("\\iiint", "integral.triple"),
        ("\\oint", "integral.cont"),
        ("\\bigcup", "union.big"),
        ("\\bigcap", "sect.big"),
        ("\\bigvee", "or.big"),
        ("\\bigwedge", "and.big"),
        ("\\bigoplus", "plus.big"),
        ("\\bigotimes", "times.big"),
        ("\\bigodot", "dot.big"),
        ("\\bigsqcup", "union.sq.big"),
        ("\\biguplus", "union.plus.big"),
        // Dots
        ("\\dots", "dots"),
        ("\\ldots", "dots"),
        ("\\cdots", "dots.h.c"),
        ("\\vdots", "dots.v"),
        ("\\ddots", "dots.down"),
        ("\\iddots", "dots.up"),
        // Misc symbols
        ("\\infty", "infinity"),
        ("\\emptyset", "emptyset"),
        ("\\varnothing", "nothing"),
        ("\\nabla", "nabla"),
        ("\\partial", "partial"),
        ("\\hbar", "planck.reduce"),
        ("\\ell", "ell"),
        ("\\Re", "Re"),
        ("\\Im", "Im"),
        ("\\aleph", "aleph"),
        ("\\forall", "forall"),
        ("\\exists", "exists"),
        ("\\nexists", "exists.not"),
        ("\\neg", "not"),
        ("\\lnot", "not"),
        ("\\angle", "angle"),
        ("\\measuredangle", "angle.arc"),
        ("\\triangleright", "triangle.stroked.r"),
        ("\\triangleleft", "triangle.stroked.l"),
        // Delimiters
        ("\\langle", "angle.l"),
        ("\\rangle", "angle.r"),
        ("\\lfloor", "floor.l"),
        ("\\rfloor", "floor.r"),
        ("\\lceil", "ceil.l"),
        ("\\rceil", "ceil.r"),
        ("\\llbracket", "bracket.l.double"),
        ("\\rrbracket", "bracket.r.double"),
        // Other common
        ("\\colon", "colon"),
        ("\\checkmark", "checkmark"),
        ("\\backslash", "\\"),
    ];
    entries.iter().cloned().collect()
});

/// LaTeX accent command -> Typst accent name.
pub static ACCENT_MAP: LazyLock<HashMap<&'static str, &'static str>> = LazyLock::new(|| {
    let entries: &[(&str, &str)] = &[
        ("\\hat", "hat"),
        ("\\tilde", "tilde"),
        ("\\dot", "dot"),
        ("\\ddot", "dot.double"),
        ("\\dddot", "dot.triple"),
        ("\\ddddot", "dot.quad"),
        ("\\acute", "acute"),
        ("\\grave", "grave"),
        ("\\bar", "macron"),
        ("\\overline", "overline"),
        ("\\breve", "breve"),
        ("\\check", "caron"),
        ("\\mathring", "circle"),
        ("\\vec", "arrow"),
        ("\\overrightarrow", "arrow.r"),
        ("\\overleftarrow", "arrow.l"),
        ("\\overleftrightarrow", "arrow.l.r"),
    ];
    entries.iter().cloned().collect()
});

/// LaTeX style command -> Typst style function.
pub static STYLE_MAP: LazyLock<HashMap<&'static str, &'static str>> = LazyLock::new(|| {
    let entries: &[(&str, &str)] = &[
        ("\\mathbf", "bold"),
        ("\\mathit", "italic"),
        ("\\mathrm", "upright"),
        ("\\mathsf", "sans"),
        ("\\mathtt", "mono"),
        ("\\mathbb", "bb"),
        ("\\mathcal", "cal"),
        ("\\mathfrak", "frak"),
        ("\\boldsymbol", "bold"),
        ("\\bm", "bold"),
    ];
    entries.iter().cloned().collect()
});

/// LaTeX operator -> Typst operator identifier.
pub static OPERATOR_MAP: LazyLock<HashMap<&'static str, &'static str>> = LazyLock::new(|| {
    let entries: &[(&str, &str)] = &[
        ("\\sin", "sin"),
        ("\\cos", "cos"),
        ("\\tan", "tan"),
        ("\\cot", "cot"),
        ("\\sec", "sec"),
        ("\\csc", "csc"),
        ("\\sinh", "sinh"),
        ("\\cosh", "cosh"),
        ("\\tanh", "tanh"),
        ("\\coth", "coth"),
        ("\\arcsin", "arcsin"),
        ("\\arccos", "arccos"),
        ("\\arctan", "arctan"),
        ("\\log", "log"),
        ("\\ln", "ln"),
        ("\\lg", "lg"),
        ("\\exp", "exp"),
        ("\\lim", "lim"),
        ("\\limsup", "limsup"),
        ("\\liminf", "liminf"),
        ("\\max", "max"),
        ("\\min", "min"),
        ("\\sup", "sup"),
        ("\\inf", "inf"),
        ("\\det", "det"),
        ("\\gcd", "gcd"),
        ("\\deg", "deg"),
        ("\\dim", "dim"),
        ("\\hom", "hom"),
        ("\\ker", "ker"),
        ("\\arg", "arg"),
        ("\\Pr", "Pr"),
        ("\\mod", "mod"),
    ];
    entries.iter().cloned().collect()
});
