// Generated by Calepin. Do not edit.

#let config = (
  enabled: true,
  results: path("results.json"),
  "image-meta": path("image-meta.json"),
  "source-dir": "themes",
  source: "themes/html_templates.typ",
  "raw-langs": ("d2", "dot", "html", "mermaid", "python", "r", "tikz"),
)
