---
title: Jinja2
---

*Calepin* uses [MiniJinja](https://github.com/mitsuhiko/minijinja), a Jinja2 template engine for Rust. The same syntax is used everywhere: in document bodies ([shortcuts](shortcuts.html)), in element templates ([elements](elements.html)), in page templates ([pages](pages.html)), and in site templates ([sites](sites.html)).

This page covers the syntax basics. If you know Jinja2 or Python's Django templates, you already know this.


# Expressions

Insert a value with double braces:

```
{{ variable }}
```

Dot notation accesses nested values:

```
{{ meta.title }}
{{ var.urls.docs }}
```


# Functions

Call functions with parentheses and keyword arguments:

```
{{ pagebreak() }}
{{ video(url="https://youtube.com/watch?v=abc") }}
{{ lipsum(paragraphs=3) }}
```


# Conditionals

```
{% if format == "html" %}
This appears only in HTML output.
{% elif format == "latex" %}
This appears only in LaTeX output.
{% else %}
This appears in all other formats.
{% endif %}
```


# Loops

```
{% for item in var.features %}
- {{ item }}
{% endfor %}
```


# Filters

Filters transform values with the pipe operator:

```
{{ meta.title | upper }}
{{ meta.title | length }}
```

MiniJinja provides built-in filters like `upper`, `lower`, `length`, `trim`, `replace`, `default`, and others. See the [MiniJinja documentation](https://docs.rs/minijinja/latest/minijinja/) for the full list.


# Comments

```
{# This is a comment and won't appear in the output. #}
```


# Raw blocks

To include literal Jinja syntax without evaluation, wrap it in {% raw %}`{% raw %}...{% endraw %}`{% endraw %}:

````
{% raw %}
{{ this is not evaluated }}
{% endraw %}
````


# Whitespace control

Add a dash to trim whitespace before or after a tag:

```
{%- if condition -%}
  compact output
{%- endif -%}
```


# Set variables

Define local variables:

```
{% set name = "World" %}
Hello, {{ name }}!
```


# Include files

Include external files:

```
{% include "header.qmd" %}
```

In document bodies, {% raw %}`{% include %}`{% endraw %} is a pre-parse directive. Included content is parsed as blocks, so code chunks and fenced divs work normally. YAML front matter in included files is stripped automatically.


# Where this syntax is used

| Context | Example | Details |
|---------|---------|---------|
| Document body | {% raw %}`{{ meta.title }}`{% endraw %} in your `.qmd` | [Shortcuts](shortcuts.html) |
| Element templates | {% raw %}`{{children}}`{% endraw %} in `_calepin/elements/div.html` | [Elements](elements.html) |
| Page templates | {% raw %}`{{body}}`{% endraw %} in `_calepin/templates/calepin.html` | [Pages](pages.html) |
| Site templates | {% raw %}`{{ page.title }}`{% endraw %} in `_templates/page.html` | [Sites](sites.html) |

The syntax is identical everywhere. The only difference is which variables and functions are available in each context.
