// Generated by Calepin. Do not edit.

#let config = (
  enabled: true,
  results: path("results.json"),
  "image-meta": path("image-meta.json"),
  "source-dir": "themes",
  source: "themes/css.typ",
  "raw-langs": ("css", "d2", "dot", "html", "mermaid", "python", "r", "sh", "text", "tikz", "toml"),
)
