name = "latex"
description = "LaTeX document output"

[target]
writer = "latex"
template = "page"
extension = "tex"
fig_extension = "pdf"
fig_formats = ["pdf", "eps", "svg", "png", "jpg"]
preview = "serve"
crossref = "latex"
toc_headings = false
modules = ["highlight", "convert_svg_pdf"]
