#!/usr/bin/env bash
set -euo pipefail

: "${HOMEBREW_TAP_GITHUB_TOKEN:?HOMEBREW_TAP_GITHUB_TOKEN is required}"

tag="${GITHUB_REF_NAME:-}"
if [[ -z "${tag}" ]]; then
  tag="$(git describe --tags --exact-match)"
fi

case "${tag}" in
  v*) ;;
  *)
    echo "expected a v-prefixed release tag, got: ${tag}" >&2
    exit 1
    ;;
esac

version="${tag#v}"
source_url="https://github.com/vincentarelbundock/calepin/archive/refs/tags/${tag}.tar.gz"
tmpdir="$(mktemp -d)"
trap 'rm -rf "${tmpdir}"' EXIT

archive="${tmpdir}/calepin-${tag}.tar.gz"
curl -fsSL "${source_url}" -o "${archive}"
if command -v sha256sum >/dev/null 2>&1; then
  sha256="$(sha256sum "${archive}" | cut -d " " -f 1)"
else
  sha256="$(shasum -a 256 "${archive}" | cut -d " " -f 1)"
fi

tap_dir="${tmpdir}/homebrew-tap"
git clone "https://x-access-token:${HOMEBREW_TAP_GITHUB_TOKEN}@github.com/vincentarelbundock/homebrew-tap.git" "${tap_dir}"
cd "${tap_dir}"

mkdir -p Formula
cat > Formula/calepin.rb <<FORMULA
# typed: false
# frozen_string_literal: true

# This file was generated by calepin's release workflow. DO NOT EDIT.
class Calepin < Formula
  desc "Preprocess Typst documents with executable code chunks"
  homepage "https://github.com/vincentarelbundock/calepin"
  url "${source_url}"
  sha256 "${sha256}"
  license "MIT"

  depends_on "rust" => :build

  def install
    system "cargo", "install", "--locked", "--path", ".", "--root", prefix, "--bin", "calepin"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/calepin --version")
  end
end
FORMULA

git add Formula/calepin.rb
git rm -f --ignore-unmatch calepin.rb

if git diff --cached --quiet; then
  echo "Homebrew formula already up to date"
  exit 0
fi

git config user.name "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
git commit -m "Update calepin formula to ${tag}"
git push origin HEAD:main
