#!/usr/bin/env bash
set -euo pipefail

# Regenerate the Scoop manifest in vincentarelbundock/scoop-bucket for a
# released tag. Called by .github/workflows/update-scoop-bucket.yml after the
# cargo-dist release workflow has published the Windows archive.
#
# The manifest points at the release's prebuilt zip rather than building from
# source, so the hash has to match the exact asset. cargo-dist publishes a
# `.sha256` next to the archive, so we use that and only fall back to hashing
# the archive ourselves if the checksum asset is missing.

: "${SCOOP_BUCKET_GITHUB_TOKEN:?SCOOP_BUCKET_GITHUB_TOKEN is required}"

tag="${CALEPIN_RELEASE_TAG:-${GITHUB_REF_NAME:-}}"
if [[ -z "${tag}" ]]; then
  tag="$(git describe --tags --exact-match)"
fi

case "${tag}" in
  v*) ;;
  *)
    echo "expected a v-prefixed release tag, got: ${tag}" >&2
    exit 1
    ;;
esac

version="${tag#v}"
archive="calepin-x86_64-pc-windows-msvc.zip"
archive_url="https://github.com/vincentarelbundock/calepin/releases/download/${tag}/${archive}"

tmpdir="$(mktemp -d)"
trap 'rm -rf "${tmpdir}"' EXIT

sha256=""
if curl -fsSL "${archive_url}.sha256" -o "${tmpdir}/${archive}.sha256"; then
  # cargo-dist writes "<hash> *<filename>".
  sha256="$(cut -d " " -f 1 "${tmpdir}/${archive}.sha256")"
fi

if ! [[ "${sha256}" =~ ^[0-9a-f]{64}$ ]]; then
  echo "no usable checksum asset; hashing ${archive} instead" >&2
  curl -fsSL "${archive_url}" -o "${tmpdir}/${archive}"
  if command -v sha256sum >/dev/null 2>&1; then
    sha256="$(sha256sum "${tmpdir}/${archive}" | cut -d " " -f 1)"
  else
    sha256="$(shasum -a 256 "${tmpdir}/${archive}" | cut -d " " -f 1)"
  fi
fi

if ! [[ "${sha256}" =~ ^[0-9a-f]{64}$ ]]; then
  echo "could not determine a sha256 for ${archive}" >&2
  exit 1
fi

bucket_dir="${tmpdir}/scoop-bucket"
git clone "https://x-access-token:${SCOOP_BUCKET_GITHUB_TOKEN}@github.com/vincentarelbundock/scoop-bucket.git" "${bucket_dir}"
cd "${bucket_dir}"

mkdir -p bucket
cat > bucket/calepin.json <<MANIFEST
{
    "##": "This file was generated by calepin's release workflow. DO NOT EDIT.",
    "version": "${version}",
    "description": "Typst-native computational notebooks: executable R, Python and diagram chunks inside a .typ document.",
    "homepage": "https://vincentarelbundock.github.io/calepin",
    "license": "MIT",
    "architecture": {
        "64bit": {
            "url": "${archive_url}",
            "hash": "${sha256}"
        }
    },
    "bin": "calepin.exe",
    "checkver": {
        "github": "https://github.com/vincentarelbundock/calepin"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/vincentarelbundock/calepin/releases/download/v\$version/calepin-x86_64-pc-windows-msvc.zip"
            }
        },
        "hash": {
            "url": "\$url.sha256"
        }
    },
    "notes": [
        "Calepin needs the Typst CLI (0.15.0 or newer) on your PATH: scoop install typst",
        "Scoop owns this copy of Calepin, so 'calepin update' does not apply. Upgrade with: scoop update calepin"
    ]
}
MANIFEST

git add bucket/calepin.json

if git diff --cached --quiet; then
  echo "Scoop manifest already up to date"
  exit 0
fi

git config user.name "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
git commit -m "Update calepin manifest to ${tag}"
git push origin HEAD:main
