[meta]
title = "Calepin"
subtitle = "A document and site generator"
author = "Vincent Arel-Bundock"
csl = "chicago-author-date"
highlight = {light = "github", dark = "nord"}

[targets.html]
base = "html"
template = "page"
extension = "html"
fig-extension = "svg"
preview = "serve"

[targets.latex]
base = "latex"
template = "page"
extension = "tex"
fig-extension = "pdf"
preview = "serve"
[targets.latex.compile]
command = "tectonic {input}"
extension = "pdf"

[targets.typst]
base = "typst"
template = "page"
extension = "typ"
fig-extension = "svg"
preview = "serve"
[targets.typst.compile]
command = "typst compile {input} {output}"
extension = "pdf"

[targets.website]
base = "html"
template = "page"
extension = "html"
fig-extension = "svg"
preview = "serve"

[targets.book]
base = "latex"
template = "page"
extension = "tex"
fig-extension = "pdf"
[targets.book.compile]
command = "tectonic {input}"
extension = "pdf"

[targets.pdf]
base = "latex"
template = "page"
extension = "tex"
fig-extension = "pdf"
[targets.pdf.compile]
command = "tectonic {input}"
extension = "pdf"

[targets.markdown]
base = "markdown"
template = "page"
extension = "md"
fig-extension = "png"
preview = "none"
