title = "Calepin"
description = "A Typst-native computational notebook and static website generator."
base_url = "https://vincentarelbundock.github.io/calepin"
logo = "assets/logo_short_2.svg"
logo_alt = "Calepin"
pdf = true
minify = true
search = "pagefind"
theme = "calepin"

generate_feeds = true

[feeds]
filenames = ["atom.xml", "rss.xml"]

[static]
include = ["assets/**"]

[navbar]

[[navbar.item]]
position = "right"
target = "https://github.com/vincentarelbundock/calepin"
label = "{icon:github}"

[executables]
python = "../.venv/bin/python"
typst = "typst"

[sidebar]
fold = false

[[sidebar.section]]
title = "Getting started"

  [[sidebar.section.item]]
  target = "index.typ"
  label = "Home"

  [[sidebar.section.item]]
  target = "getting-started/install.typ"
  label = "Install"

  [[sidebar.section.item]]
  target = "getting-started/config.typ"
  label = "Configuration"

[[sidebar.section]]
title = "Notebooks"

  [[sidebar.section.item]]
  target = "notebooks/code_execution.typ"
  label = "Code execution"

  [[sidebar.section.item]]
  target = "notebooks/figures.typ"
  label = "Figures and tables"

  [[sidebar.section.item]]
  target = "notebooks/cross-references.typ"
  label = "Cross-references"

  [[sidebar.section.item]]
  target = "notebooks/parameters.typ"
  label = "Parameters"

  [[sidebar.section.item]]
  target = "notebooks/themes.typ"
  label = "Themes"

  [[sidebar.section.item]]
  target = "notebooks/example.typ"
  label = "Example notebook"

[[sidebar.section]]
title = "Websites"

  [[sidebar.section.item]]
  target = "websites/websites.typ"
  label = "Overview"

  [[sidebar.section.item]]
  target = "websites/config.typ"
  label = "Configuration"

  [[sidebar.section.item]]
  target = "websites/themes.typ"
  label = "Themes"

  [[sidebar.section.item]]
  target = "websites/web_components.typ"
  label = "Web components"



[[sidebar.section]]
title = "More"

  [[sidebar.section.item]]
  target = "tips.typ"
  label = "Tips & tricks"

  [[sidebar.section.item]]
  target = "websites/health.typ"
  label = "Health"

  [[sidebar.section.item]]
  target = "reference/cli.typ"
  label = "CLI reference"
