title = "Calepin"
description = "A Typst-native computational notebook and static website generator."
base_url = "https://vincentarelbundock.github.io/calepin"
logo = "assets/logo_short_2.svg"
logo_alt = "Calepin"
github_url = "https://github.com/vincentarelbundock/calepin"
pdf = true

[executables]
python = "../.venv/bin/python"
typst = "typst"

[sidebar]

[[sidebar.section]]
title = "Getting started"

  [[sidebar.section.item]]
  path = "index.typ"
  label = "Home"

  [[sidebar.section.item]]
  path = "getting-started/install.typ"
  label = "Install"

  [[sidebar.section.item]]
  path = "getting-started/config.typ"
  label = "Configuration"

[[sidebar.section]]
title = "Notebooks"

  [[sidebar.section.item]]
  path = "notebooks/parameterized_notebooks.typ"
  label = "Parameterized notebooks"

  [[sidebar.section.item]]
  path = "notebooks/tables_and_figures.typ"
  label = "Tables and figures"

  [[sidebar.section.item]]
  path = "notebooks/crossreferences.typ"
  label = "Cross-references"

  [[sidebar.section.item]]
  path = "notebooks/templates.typ"
  label = "HTML themes"

  [[sidebar.section.item]]
  path = "notebooks/example.typ"
  label = "Example notebook"

[[sidebar.section]]
title = "Code execution"

  [[sidebar.section.item]]
  path = "execution/supported-languages.typ"
  label = "Languages"

  [[sidebar.section.item]]
  path = "execution/options.typ"
  label = "Options"

[[sidebar.section]]
title = "Website generator"

  [[sidebar.section.item]]
  path = "websites/websites.typ"
  label = "Overview"

  [[sidebar.section.item]]
  path = "websites/website-config.typ"
  label = "Configuration"

  [[sidebar.section.item]]
  path = "websites/website-themes.typ"
  label = "Themes"

[[sidebar.section]]
title = "Reference"

  [[sidebar.section.item]]
  path = "reference/cli.typ"
  label = "Command line"
