title = "Calepin"
description = "A Typst-native computational notebook and static website generator."
base_url = "https://vincentarelbundock.github.io/calepin"
logo = "assets/logo_short.svg"
logo_alt = "Calepin"
pdf = true
minify = true
# search = "pagefind"
highlight-light = "assets/Catppuccin Latte.tmTheme"
highlight-dark = "assets/Catppuccin Mocha.tmTheme"

generate_feeds = true

[feeds]
filenames = ["atom.xml", "rss.xml"]

[static]
include = ["assets/**", "index.typ"]

[[menus.main]]
target = "getting-started/install.typ"
label = "Documentation"

[[menus.social]]
target = "https://github.com/vincentarelbundock/calepin"
label = "{icon:github}"

[executables]
python = "../.venv/bin/python"
typst = "typst"

[sidebar]
fold = false

[[sidebar.section]]
title = "Getting started"

  [[sidebar.section.item]]
  target = "getting-started/install.typ"

  [[sidebar.section.item]]
  target = "getting-started/config.typ"

  [[sidebar.section.item]]
  target = "compile_watch_serve.typ"

[[sidebar.section]]
title = "Notebooks"

  [[sidebar.section.item]]
  target = "notebooks/notebooks.typ"

  [[sidebar.section.item]]
  target = "notebooks/code_execution.typ"

  [[sidebar.section.item]]
  target = "notebooks/figures.typ"

  [[sidebar.section.item]]
  target = "notebooks/cross-references.typ"

  [[sidebar.section.item]]
  target = "notebooks/parameters.typ"

  [[sidebar.section.item]]
  target = "notebooks/diagrams.typ"

[[sidebar.section]]
title = "Websites"

  [[sidebar.section.item]]
  target = "websites/websites.typ"

  [[sidebar.section.item]]
  target = "websites/config.typ"

  [[sidebar.section.item]]
  target = "websites/elements.typ"



[[sidebar.section]]
title = "More"

  [[sidebar.section.item]]
  target = "themes.typ"

  [[sidebar.section.item]]
  target = "tips.typ"

  [[sidebar.section.item]]
  target = "websites/health.typ"

  [[sidebar.section.item]]
  target = "reference/cli.typ"
