// Generated by Calepin. Do not edit.

#import "/.calepin/calepin.typ" as runtime
#import "runtime-config.typ": config

#let _bound = runtime.bind(config)
#let pages = _bound.pages
#let setup = _bound.setup
#let chunk = _bound.chunk
#let inline = _bound.inline
#let results = _bound.results
#let chunk_from_raw_plain = _bound.chunk_from_raw_plain
#let code-block = _bound.code-block
#let elements = _bound.elements
#let asset-href = _bound.asset-href
#let document = _bound.document
