// Generated by Calepin. Do not edit.

#let config = (
  enabled: true,
  results: path("results.json"),
  "image-meta": path("image-meta.json"),
  "source-dir": "themes",
  source: "themes/themes.typ",
  "raw-langs": ("d2", "dot", "mermaid", "python", "r", "sh", "text", "tikz", "toml"),
)
