mod chunk_options;
pub(crate) mod cli;
pub(crate) mod compile;
mod crossref;
mod execute;
mod fence_label;
mod introspect;
pub(crate) mod io;
pub(crate) mod model;
pub(crate) mod paths;
pub(crate) mod preprocess;
mod query;
mod results;
mod run;
mod runtime;
mod source_rewrite;
mod sync;
#[cfg(test)]
mod testfixtures;
pub(crate) mod version;
mod watch;
